---
abstract: 'TheBestSpinner API'
author:
  - 'Fayland Lam <fayland@gmail.com>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.030
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-TheBestSpinner
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  LWP::UserAgent: 0
  MIME::Base64: 0
  PHP::Serialization: 0
  perl: 5.008005
version: 0.01
